import type { Metadata } from 'next'
import { Signika } from 'next/font/google'
import './globals.css'

const inter = Signika({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: 'Transportes Valso',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
