import type { Metadata } from 'next'
import { Signika } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/header/Index'
import { Footer } from '@/components/footer/Index'

const inter = Signika({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: 'Transportes Valso',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
