import type { Metadata } from 'next'
import { Signika, Roboto } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/header/Index'
import { Footer } from '@/components/Footer/Index'

const signika = Signika({ subsets: ["latin"] })

const roboto = Roboto({ subsets: ["latin"], weight: "400", variable: "--font-roboto", })

export const metadata: Metadata = {
  title: 'Transportes Valso',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={`${signika.className} ${roboto.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
